"""empty message

Revision ID: 26f296dff6cd
Revises: 5ecc252e8947
Create Date: 2021-11-29 21:33:02.793700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f296dff6cd'
down_revision = '5ecc252e8947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('post_img', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'post_img')
    # ### end Alembic commands ###
