"""empty message

Revision ID: ef2d0832ca91
Revises: 60a20bc4ec69
Create Date: 2021-12-01 20:04:14.939920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef2d0832ca91'
down_revision = '60a20bc4ec69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggestion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=1024), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggestion_email'), 'suggestion', ['email'], unique=False)
    op.create_index(op.f('ix_suggestion_username'), 'suggestion', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suggestion_username'), table_name='suggestion')
    op.drop_index(op.f('ix_suggestion_email'), table_name='suggestion')
    op.drop_table('suggestion')
    # ### end Alembic commands ###
